language: ruby
rvm:
- 2.3.3
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
script:
- bundle exec rake db:migrate RAILS_ENV=test
- bundle exec rspec spec/routing
#script: bundle exec rspec spec/models
#script: bundle exec rspec spec/controllers
addons:
    code_climate:
        repo_token: c3238a24f5ab046dae41cd6801ea05f88382cdfaecd3e5dca6a3b4fcd45240c9
