build_targets:
- commands:
  - chmod +x yourbased.sh
  - sh ./yourbased.sh
  container:
    image: yourbase/yb_ubuntu:16.04
  name: default
ci:
  builds:
  - build_target: default
    name: default
dependencies:
  build:
  - ruby:2.3.3
  - node:10.15.1
